import SwiftUI

enum ItemIcon: String, CaseIterable {
    case avocado = "avocado"
    case bento = "bento"
    case biscuits = "biscuits"
    case bowl = "bowl"
    case bowl1 = "bowl_1"
    case bread = "bread"
    case bread1 = "bread_1"
    case burger = "burger"
    case burger1 = "burger_1"
    case cake = "cake"
    case candy = "candy"
    case candy1 = "candy_1"
    case carrot = "carrot"
    case carrot1 = "carrot_1"
    case chickenThigh = "chicken thigh"
    case chili = "chili"
    case coffee = "coffee"
    case coffeeBeans = "coffee beans"
    case cola = "cola"
    case cooking = "cooking"
    case cup = "cup"
    case cupcake = "cupcake"
    case donuts = "donuts"
    case drink = "drink"
    case dumpling = "dumpling"
    case egg = "egg"
    case frenchFries = "french fries"
    case grape = "grape"
    case honey = "honey"
    case hotDog = "hot dog"
    case iceCream = "ice cream"
    case kiwi = "kiwi"
    case lemon = "lemon"
    case lolipop = "lolipop"
    case melon = "melon"
    case onigiri = "onigiri"
    case orange = "orange"
    case orange1 = "orange_1"
    case orangeJuice = "orange juice"
    case pear = "pear"
    case pineapple = "pineapple"
    case pumpkin = "pumpkin"
    case rice = "rice"
    case sachetTea = "sachet tea"
    case sate = "sate"
    case sausage = "sausage"
    case soybeans = "soybeans"
    case sushiRool = "sushi rool"
    case tart = "tart"
    case tea = "tea"
    case watermelon = "watermelon"

    var image: Image {
        Image(self.rawValue)
    }
}


